name: Agda CI

on: workflow_dispatch

jobs:
  agda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Agda
        run: |
          sudo apt update
          sudo apt install -y agda git

      - name: Fetch Agda standard library
        working-directory: src
        run: |
          git clone --depth 1 https://github.com/agda/agda-stdlib.git
          echo "$PWD/agda-stdlib/standard-library.agda-lib" > agda-lib

      - name: Verify Agda files
        working-directory: src
        run: |
          agda --ignore-interfaces --without-K --library-file=agda-lib All.agda
