name: Agda CI

on: workflow_dispatch

jobs:
  agda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Installiere Agda (latest) + die empfohlene Standardbibliothek
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: latest
          agda-stdlib-version: recommended

      # Hauptmodul checken (siehe oben: All.agda importiert alles)
      - run: agda --ignore-interfaces --without-K All.agda
        working-directory: src
