name: Agda CI

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: latest
          agda-stdlib-version: recommended

      - name: Register drife.agda-lib
        working-directory: src
        run: |
          echo "$PWD/drife.agda-lib" >> $HOME/.agda/libraries
          echo drife > $HOME/.agda/defaults

      - name: Compile project
        working-directory: src
        run: |
          agda --ignore-interfaces --without-K -i . All.agda
