name: Agda CI

on: workflow_dispatch

jobs:
  agda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y agda agda-stdlib

      - name: Set up Agda library file
        working-directory: src
        run: |
          echo '/usr/share/agda-stdlib/standard-library.agda-lib' > agda-lib

      - name: Verify Agda files
        working-directory: src
        run: |
          agda --ignore-interfaces --without-K --library-file=agda-lib All.agda
