name: Agda CI

on: workflow_dispatch

jobs:
  agda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y agda agda-stdlib || true

      - name: Find Agda standard library path
        run: |
          find /usr -name standard-library.agda-lib || true

      - name: Set up Agda library file
        working-directory: src
        run: |
          if [ -f /usr/share/agda-stdlib/standard-library.agda-lib ]; then
            echo '/usr/share/agda-stdlib/standard-library.agda-lib' > agda-lib;
          elif [ -f /usr/lib/agda-stdlib/standard-library.agda-lib ]; then
            echo '/usr/lib/agda-stdlib/standard-library.agda-lib' > agda-lib;
          else
            echo 'Agda standard library not found!' && exit 1;
          fi

      - name: Verify Agda files
        working-directory: src
        run: |
          agda --ignore-interfaces --without-K --library-file=agda-lib All.agda

