name: Agda CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  agda-check:
    runs-on: ubuntu-latest
    container: "gallais/agda:2.6.4"
    steps:
      - uses: actions/checkout@v3
      - run: agda --ignore-interfaces --without-K src/*.agda
      - run: agda --html --ignore-interfaces *.agda

      - name: Generate HTML (optional)
        working-directory: src
        run: |
          agda --html --ignore-interfaces *.agda
