name: Agda CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  agda-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y agda agda-stdlib

      - name: Verify Agda files
        working-directory: src
        run: |
          # Kompiliere alle .agda-Dateien (ohne HTML-Ausgabe)
          agda --ignore-interfaces --without-K *.agda

      - name: Generate HTML (optional)
        working-directory: src
        run: |
          agda --html --ignore-interfaces *.agda
